configfile: "config/config.yaml"

include: "rules/setup.smk"
include: "rules/download.smk"
include: "rules/parse.smk"
include: "rules/qc.smk"
include: "rules/dimred.smk"
include: "rules/annotate.smk"

rule all:
    input:
        "data/processed/annotated.h5ad" 
        