geo:
  accession: GSE148071
  base_url: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE148nnn/GSE148071/suppl/
  matrix_url: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE148nnn/GSE148071/matrix/GSE148071_series_matrix.txt.gz

files:
  raw_tar: GSE148071_RAW.tar
  series_matrix: GSE148071_series_matrix.txt.gz

paths:
  raw_dir: data/raw

qc:
  min_genes:  200     # remove empty/dying cells
  max_genes:  5000    # remove likely doublets (according to the publication)
  max_pct_mt: 30      # remove dying cells (according to the publication)
  min_cells:  3       # remove genes expressed in fewer than 3 cells

dimred:
  n_hvgs:      3000    # HVGs for scVI input
  n_pcs:       50      # PCA components
  n_latent:    30      # scVI latent dimensions
  n_epochs:    400     # max training epochs (early stopping active)
  batch_size:  128     # scVI minibatch size
  n_neighbors: 15      # neighborhood graph for UMAP